name: Clean Build

on:
  workflow_dispatch:

jobs:
  clean-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean and Build
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon
